import Fluent

struct CreateSchema: AsyncMigration {
    func prepare(on db: Database) async throws {
        try await db.schema(User.schema)
            .id()
            .field("provider", .string, .required)
            .field("provider_user_id", .string, .required)
            .field("display_name", .string, .required)
            .field("username", .string, .required)
            .field("avatar_url", .string)
            .field("home_area", .string, .required)
            .field("transport", .string, .required)
            .field("max_travel_minutes", .int, .required)
            .field("budget", .int, .required)
            .field("interests", .array(of: .string), .required)
            .field("default_sharing", .string, .required)
            .field("created_at", .datetime)
            .unique(on: "username")
            .unique(on: "provider", "provider_user_id")
            .create()

        try await db.schema(UserToken.schema)
            .id()
            .field("value", .string, .required)
            .field("user_id", .uuid, .required, .references(User.schema, "id"))
            .unique(on: "value")
            .create()

        try await db.schema(FriendEdge.schema)
            .id()
            .field("requester_id", .uuid, .required, .references(User.schema, "id"))
            .field("recipient_id", .uuid, .required, .references(User.schema, "id"))
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await db.schema(MeetupSession.schema)
            .id()
            .field("organizer_id", .uuid, .required, .references(User.schema, "id"))
            .field("type", .string, .required)
            .field("window_kind", .string, .required)
            .field("custom_start", .datetime)
            .field("max_budget", .int)
            .field("indoor_outdoor", .string, .required)
            .field("dietary", .array(of: .string), .required)
            .field("vibe", .string, .required)
            .field("max_travel_minutes", .int)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await db.schema(SessionParticipant.schema)
            .id()
            .field("session_id", .uuid, .required, .references(MeetupSession.schema, "id"))
            .field("user_id", .uuid, .required, .references(User.schema, "id"))
            .field("is_available", .bool)
            .field("sharing", .string)
            .field("lat", .double)
            .field("lon", .double)
            .field("manual_place", .string)
            .field("responded_at", .datetime)
            .create()

        try await db.schema(SuggestionOption.schema)
            .id()
            .field("session_id", .uuid, .required, .references(MeetupSession.schema, "id"))
            .field("rank", .int, .required)
            .field("venue_name", .string, .required)
            .field("area_name", .string, .required)
            .field("category", .string, .required)
            .field("lat", .double, .required)
            .field("lon", .double, .required)
            .field("time", .datetime, .required)
            .field("explanation", .string, .required)
            .field("fairness", .double, .required)
            .field("interest", .double, .required)
            .field("budget_fit", .double, .required)
            .create()

        try await db.schema(Vote.schema)
            .id()
            .field("session_id", .uuid, .required, .references(MeetupSession.schema, "id"))
            .field("suggestion_id", .uuid, .required, .references(SuggestionOption.schema, "id"))
            .field("user_id", .uuid, .required, .references(User.schema, "id"))
            .unique(on: "session_id", "user_id")
            .create()

        try await db.schema(DeviceToken.schema)
            .id()
            .field("user_id", .uuid, .required, .references(User.schema, "id"))
            .field("token", .string, .required)
            .field("created_at", .datetime)
            .unique(on: "token")
            .create()

        try await db.schema(BlockedUser.schema)
            .id()
            .field("blocker_id", .uuid, .required, .references(User.schema, "id"))
            .field("blocked_id", .uuid, .required, .references(User.schema, "id"))
            .field("is_report", .bool, .required)
            .field("reason", .string)
            .field("created_at", .datetime)
            .create()

        try await db.schema(ConfirmedMeetup.schema)
            .id()
            .field("session_id", .uuid, .required)
            .field("title", .string, .required)
            .field("venue_name", .string, .required)
            .field("area_name", .string, .required)
            .field("lat", .double, .required)
            .field("lon", .double, .required)
            .field("time", .datetime, .required)
            .field("explanation", .string, .required)
            .field("attendee_names", .array(of: .string), .required)
            .field("created_at", .datetime)
            .create()
    }

    func revert(on db: Database) async throws {
        try await db.schema(ConfirmedMeetup.schema).delete()
        try await db.schema(BlockedUser.schema).delete()
        try await db.schema(DeviceToken.schema).delete()
        try await db.schema(Vote.schema).delete()
        try await db.schema(SuggestionOption.schema).delete()
        try await db.schema(SessionParticipant.schema).delete()
        try await db.schema(MeetupSession.schema).delete()
        try await db.schema(FriendEdge.schema).delete()
        try await db.schema(UserToken.schema).delete()
        try await db.schema(User.schema).delete()
    }
}
